version: "3.5"

services:
  app:
    image: golang:1.17-stretch
    volumes:
      - ./:/go/src/app
      - ./data/go/pkg/mod:/go/pkg/mod
      - ./data/go/bin:/go/bin
    environment:
      - GO111MODULE=on
    working_dir: /go/src/app
    tty: true